@Avatar_3D_Sentry_HostAddress = http://localhost:5216

POST {{Avatar_3D_Sentry_HostAddress}}/Avatar/anunciar
Content-Type: application/json

{
  "empresa": "ACME",
  "sede": "central",
  "modulo": "A",
  "turno": "mañana",
  "nombre": "Juan Pérez"
}

###
